services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080