spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/demo
    username: root
    password: root
    driverClassName: org.postgresql.Driver

api:
  security:
    token:
      secret: my-secret-key-from-video